//! Embedding CLI commands: `ctx embed pending` and `ctx embed rebuild`.
//!
//! Manages the embedding lifecycle:
//!
//! - **[`run_embed_pending`]** — backfill missing or stale embeddings
//! - **[`run_embed_rebuild`]** — delete and regenerate all embeddings
//! - **[`embed_chunks_inline`]** — embed chunks during sync (non-fatal)
//!
//! # Staleness Detection
//!
//! Each chunk's text is hashed (SHA-256). When the hash in the `embeddings`
//! table differs from the chunk's current hash, the embedding is considered
//! stale and will be re-generated by `embed pending`.
//!
//! # Batching
//!
//! Embeddings are generated in batches (configurable via `embedding.batch_size`
//! or `--batch-size` flag). Each batch is a single API call to the embedding
//! provider. Failed batches are logged but don't abort the entire operation.

use anyhow::{bail, Result};
use context_harness_core::store::Store;

use crate::app_store::{hash_text, AppStore, SqliteAppStore};
use crate::config::Config;
use crate::embedding;

/// Backfill embeddings for chunks that are missing or have stale hashes.
///
/// Finds all chunks where either:
/// 1. No embedding exists for the current model, or
/// 2. The embedding's stored hash doesn't match the chunk's current text hash.
///
/// # Arguments
///
/// * `config` — Application configuration.
/// * `limit` — Optional cap on the number of chunks to process.
/// * `batch_size_override` — Override the config's `embedding.batch_size`.
/// * `dry_run` — If `true`, report counts without writing anything.
///
/// # Errors
///
/// Returns an error if the embedding provider is disabled.
pub async fn run_embed_pending(
    config: &Config,
    limit: Option<usize>,
    batch_size_override: Option<usize>,
    dry_run: bool,
) -> Result<()> {
    if !config.embedding.is_enabled() {
        bail!("Embedding provider is disabled. Set [embedding] provider in config.");
    }

    let provider = embedding::create_provider(&config.embedding)?;
    let model_name = provider.model_name().to_string();
    let store = SqliteAppStore::connect(config).await?;
    let batch_size = batch_size_override.unwrap_or(config.embedding.batch_size);

    // Find chunks missing embeddings or with stale hashes
    let pending = store.find_pending_chunks(&model_name, limit).await?;

    if dry_run {
        println!("embed pending (dry-run)");
        println!("  chunks needing embeddings: {}", pending.len());
        return Ok(());
    }

    if pending.is_empty() {
        println!("embed pending");
        println!("  all chunks up to date");
        return Ok(());
    }

    let total = pending.len();
    let mut embedded = 0u64;
    let mut failed = 0u64;

    for batch in pending.chunks(batch_size) {
        let texts: Vec<String> = batch.iter().map(|p| p.text.clone()).collect();

        match embedding::embed_texts(provider.as_ref(), &config.embedding, &texts).await {
            Ok(vectors) => {
                for (item, vec) in batch.iter().zip(vectors.iter()) {
                    store
                        .upsert_embedding(
                            &item.chunk_id,
                            &item.document_id,
                            vec,
                            &model_name,
                            provider.dims(),
                            &item.text_hash,
                        )
                        .await?;
                    embedded += 1;
                }
            }
            Err(e) => {
                eprintln!("Warning: embedding batch failed: {}", e);
                failed += batch.len() as u64;
            }
        }
    }

    println!("embed pending");
    println!("  total pending: {}", total);
    println!("  embedded: {}", embedded);
    println!("  failed: {}", failed);

    store.close().await;
    Ok(())
}

/// Delete all embeddings and regenerate for all chunks.
///
/// Clears both the `embeddings` metadata table and the `chunk_vectors`
/// blob table, then re-embeds every chunk in the database.
///
/// # Arguments
///
/// * `config` — Application configuration.
/// * `batch_size_override` — Override the config's `embedding.batch_size`.
///
/// # Errors
///
/// Returns an error if the embedding provider is disabled.
pub async fn run_embed_rebuild(config: &Config, batch_size_override: Option<usize>) -> Result<()> {
    if !config.embedding.is_enabled() {
        bail!("Embedding provider is disabled. Set [embedding] provider in config.");
    }

    let provider = embedding::create_provider(&config.embedding)?;
    let model_name = provider.model_name().to_string();
    let store = SqliteAppStore::connect(config).await?;
    let batch_size = batch_size_override.unwrap_or(config.embedding.batch_size);

    // Delete all existing embeddings
    store.clear_embeddings().await?;

    println!("embed rebuild — cleared existing embeddings");

    // Get all chunks
    let all_chunks = store.find_pending_chunks(&model_name, None).await?;

    if all_chunks.is_empty() {
        println!("  no chunks to embed");
        store.close().await;
        return Ok(());
    }

    let total = all_chunks.len();
    let mut embedded = 0u64;
    let mut failed = 0u64;

    for batch in all_chunks.chunks(batch_size) {
        let texts: Vec<String> = batch.iter().map(|p| p.text.clone()).collect();

        match embedding::embed_texts(provider.as_ref(), &config.embedding, &texts).await {
            Ok(vectors) => {
                for (item, vec) in batch.iter().zip(vectors.iter()) {
                    store
                        .upsert_embedding(
                            &item.chunk_id,
                            &item.document_id,
                            vec,
                            &model_name,
                            provider.dims(),
                            &item.text_hash,
                        )
                        .await?;
                    embedded += 1;
                }
            }
            Err(e) => {
                eprintln!("Warning: embedding batch failed: {}", e);
                failed += batch.len() as u64;
            }
        }
    }

    println!("embed rebuild");
    println!("  total chunks: {}", total);
    println!("  embedded: {}", embedded);
    println!("  failed: {}", failed);

    store.close().await;
    Ok(())
}

/// Embed chunks during sync (inline). Non-fatal on failure.
///
/// Called by [`crate::ingest::run_sync`] after chunking each document.
/// Checks each chunk for existing, up-to-date embeddings before
/// calling the provider, avoiding redundant API calls.
///
/// # Returns
///
/// A tuple `(embedded, pending)`:
/// - `embedded` — number of chunks successfully embedded (or already up-to-date)
/// - `pending` — number of chunks that failed to embed
pub async fn embed_chunks_inline(
    config: &Config,
    store: &impl AppStore,
    chunks: &[crate::models::Chunk],
) -> (u64, u64) {
    if !config.embedding.is_enabled() {
        return (0, 0);
    }

    let provider = match embedding::create_provider(&config.embedding) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("Warning: could not create embedding provider: {}", e);
            return (0, chunks.len() as u64);
        }
    };

    let model_name = provider.model_name().to_string();
    let mut embedded = 0u64;
    let mut pending = 0u64;

    for batch in chunks.chunks(config.embedding.batch_size) {
        // Check which chunks need embedding
        let mut need_embedding = Vec::new();
        for chunk in batch {
            let text_hash = hash_text(&chunk.text);
            let existing = store
                .get_embedding_hash(&chunk.id, &model_name)
                .await
                .unwrap_or(None);

            if existing.as_deref() == Some(&text_hash) {
                // Already up to date
                embedded += 1;
                continue;
            }

            need_embedding.push((chunk, text_hash));
        }

        if need_embedding.is_empty() {
            continue;
        }

        let texts: Vec<String> = need_embedding.iter().map(|(c, _)| c.text.clone()).collect();

        match embedding::embed_texts(provider.as_ref(), &config.embedding, &texts).await {
            Ok(vectors) => {
                for ((chunk, text_hash), vec) in need_embedding.iter().zip(vectors.iter()) {
                    if let Err(e) = store
                        .upsert_embedding(
                            &chunk.id,
                            &chunk.document_id,
                            vec,
                            &model_name,
                            provider.dims(),
                            text_hash,
                        )
                        .await
                    {
                        eprintln!("Warning: failed to store embedding for {}: {}", chunk.id, e);
                        pending += 1;
                    } else {
                        embedded += 1;
                    }
                }
            }
            Err(e) => {
                eprintln!("Warning: embedding batch failed: {}", e);
                pending += need_embedding.len() as u64;
            }
        }
    }

    (embedded, pending)
}
